version: '3.4'

services:
  encord.accountservice:
    image: enes1/encordaccountservice
    build:
      context: .
      dockerfile: Encord.AccountService/Dockerfile

  encord.guildservice:
    image: enes1/encordguildservice
    build:
      context: .
      dockerfile: Encord.GuildService/Dockerfile


  encord.apigateway:
    image: enes1/encordapigateway
    build:
      context: .
      dockerfile: Encord.APIGateway/Dockerfile

