version: '3.4'

services:
  encord.channelservice:
    image: enes1/encordchannelservice
    build:
      context: .
      dockerfile: Encord.ChannelService/Dockerfile

  encord.accountservice:
    image: enes1/encordaccountservice
    build:
      context: .
      dockerfile: Encord.AccountService/Dockerfile


  encord.apigateway:
    image: enes1/encordapigateway
    build:
      context: .
      dockerfile: Encord.APIGateway/Dockerfile


  encord.guildservice:
    image: enes1/encordguildservice
    build:
      context: .
      dockerfile: Encord.GuildService/Dockerfile

